### ISSUE TITLE
Unable to add UEFA Euros

### ISSUE THREAD

**Issue by coleburg** [vasqued2/ha-teamtracker#158]
Has anyone had any success adding the Euros to Team Tracker?  Ive tried ENG as the team and uefa.euro as the league but no joy.

thank you

**Comment by coleburg** [comment]
resolved

**Comment by ostracizado** [comment]
How? I keep getting "NOT_FOUND" for every team. Even when I deleted the integration and yaml config & installed it again and added through the integration.

**Comment by coleburg** [comment]
league, set to custom, team, I used ENG, conference number leave blank, next page, set sport path to soccer and league path to uefa.euro

**Comment by ruudvanstrijp** [comment]
Unfortunately, this doesn't work for me. I tried setting it up just as you described but it still shows as NOT_FOUND:

![image](https://github.com/vasqued2/ha-teamtracker/assets/28410090/e662d4da-46b4-43c3-b35c-cee7eb7b4fb3)
![image](https://github.com/vasqued2/ha-teamtracker/assets/28410090/2133a889-ce95-4f43-98a6-80d1fb0a558e)
![image](https://github.com/vasqued2/ha-teamtracker/assets/28410090/e3e461d3-16d7-4bf0-83b6-05a2b40eecd7)
![image](https://github.com/vasqued2/ha-teamtracker/assets/28410090/19aad672-5c2d-4094-bde0-d68bd2c9261d)

**Comment by ruudvanstrijp** [comment]
The API does seem to work:
https://site.api.espn.com/apis/site/v2/sports/soccer/uefa.euro/teams
https://site.api.espn.com/apis/site/v2/sports/soccer/uefa.euro/teams/ned/

**Comment by coleburg** [comment]
Hi, mine shows 

![IMG_1331](https://github.com/vasqued2/ha-teamtracker/assets/13885439/fa336b06-de93-427d-ad38-0dfc82e9a649)
![IMG_1332](https://github.com/vasqued2/ha-teamtracker/assets/13885439/aa07a5af-578c-4539-ae96-71b3f07689fd)

It won’t find a game just yet as it’s too far away, but the fact it has the logo shows it’s working, I should imagine in the next couple days it will display our first game.

**Comment by ruudvanstrijp** [comment]
Ok cool, tnx! I'll see if data starts populating after this weekend, that'll be within a week from the first matches.

**Comment by ruudvanstrijp** [comment]
It started to work now, so indeed it needed some time!
